def stageRetryCount = 3

pipeline {
    
    agent any
    
    environment {
        DATAPROC_TELEPORT_WEBHOOK_URL = credentials('dataproc-teleport-webhook-url')

        TEST_JDBC_URL = credentials('env-test-jdbc-url')

        GIT_BRANCH_LOCAL = sh (
            script: "echo $branchName | sed -e 's|origin/||g' | sed -e 's|^null\$|main|'",  // Remove "origin/" and set the default branch to main
            returnStdout: true
        ).trim()
    }
    
    stages {
        stage('Checkout') {
            steps{
                git branch: "${GIT_BRANCH_LOCAL}", changelog: false, poll: false, url: 'https://github.com/GoogleCloudPlatform/dataproc-templates/'    
            }
        }
        stage('Build'){
            steps {
                    catchError {
                        sh '''
                            python3.8 -m pip install --user virtualenv

                            python3.8 -m venv env
                            source env/bin/activate
                            
                            export PACKAGE_EGG_FILE=dist/dataproc_templates_distribution.egg

                            cd python
                            python setup.py bdist_egg --output=$PACKAGE_EGG_FILE

                            cd ../notebooks
                            pip3 install -r requirements.txt
                        '''
                    }
            }
        }
        stage('Parallel Execution'){
            parallel{
                stage('MYSQL TO SPANNER') {
                    steps{
                        retry(count: stageRetryCount) {
                            sh '''

                                source env/bin/activate

                                export GCS_STAGING_LOCATION=gs://dataproc-templates/integration-testing
                                export JARS="gs://datproc_template_nk/jars/mysql-connector-java-8.0.29.jar,gs://datproc_template_nk/jars/postgresql-42.2.6.jar,gs://datproc_template_nk/jars/mssql-jdbc-6.4.0.jre8.jar"
                                export SKIP_BUILD=true

                                # Extract host
                                TEST_JDBC_host=$(echo "$TEST_JDBC_URL" | sed -E 's/jdbc:mysql:\/\/([^:]+):.*/\1/')
                                # Extract database
                                TEST_JDBC_database=$(echo "$TEST_JDBC_URL" | sed -E 's/.*\/([^?]+)\?.*/\1/')
                                # Extract user
                                TEST_JDBC_user=$(echo "$TEST_JDBC_URL" | sed -E 's/.*\?user=([^&]+)&.*/\1/')
                                # Extract password
                                TEST_JDBC_password=$(echo "$TEST_JDBC_URL" | sed -E 's/.*&password=([^&]+).*/\1/')

                                cd notebooks

                                python3 run_notebook.py --script=MYSQLTOSPANNER \
                                                        --mysql.host="$TEST_JDBC_host" \
                                                        --mysql.port="3306" \
                                                        --mysql.username="$TEST_JDBC_user" \
                                                        --mysql.password="$TEST_JDBC_password" \
                                                        --mysql.database="$TEST_JDBC_database" \
                                                        --mysql.table.list="employee" \
                                                        --mysql.read.partition.columns="{}" \
                                                        --spanner.instance="dataproc-spark-test" \
                                                        --spanner.database="spark-ci-db" \
                                                        --spanner.table.primary.keys="{\"employee\":\"empno\"}"

                            '''
                        }
                    }
                }
            }
        }
    }
    post {
        always{
            script {
                if( env.GIT_BRANCH_LOCAL == 'main' ){
                    googlechatnotification url: DATAPROC_TELEPORT_WEBHOOK_URL,
                    message: 'Jenkins: ${JOB_NAME}\nBuild status is ${BUILD_STATUS}\nSee ${BUILD_URL}\n',
                    notifyFailure: 'true',
                    notifyAborted: 'true',
                    notifyUnstable: 'true',
                    notifyNotBuilt: 'true',
                    notifyBackToNormal: 'true'
                }
            }
        }
    }
}
