PROJECT_ID_PROP = "project.id"

GCS_BQ_INPUT_LOCATION = "gcs.bigquery.input.location"
GCS_OUTPUT_DATASET_NAME = "gcs.bigquery.output.dataset"
GCS_BQ_INPUT_FORMAT = "gcs.bigquery.input.format"
GCS_OUTPUT_TABLE_NAME = "gcs.bigquery.output.table"
GCS_BQ_CSV_FORMAT = "csv"
GCS_BQ_AVRO_FORMAT = "avro"
GCS_BQ_PRQT_FORMAT = "parquet"
GCS_BQ_CSV_HEADER = "header"
GCS_BQ_OUTPUT_FORMAT = "com.google.cloud.spark.bigquery"
GCS_BQ_CSV_INFER_SCHEMA = "inferSchema"
GCS_BQ_TEMP_BUCKET = "temporaryGcsBucket"
GCS_BQ_LD_TEMP_BUCKET_NAME = "gcs.bigquery.temp.bucket.name"
GCS_BQ_OUTPUT = "table"
GCS_BQ_AVRO_EXTD_FORMAT = "com.databricks.spark.avro"