name: trigger jenkins job
on: workflow_dispatch
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://dataproctemplatesci.com"
        user: "admin"
        token: ${{ secrets.JENKINS_API_TOKEN }}
        job: "dataproc-templates-build/job/integration-tests-python"
